var examples = [
  "Default*(kabs*C0)",
  "(-vabs)/Default",
  "k3*gal+k1*lac/K_l+k2*alac/K_a+k44*x1+k44*x2",
  "V___1___+V___2___-V___3___-V___4___",
  "1+K2_H1_D/10^(-6.3)+10^(-6.3)/K2_H2_D",
  "alf_pH_D*(1+NAD/Kd_NAD_D+NADH/Kd_NADH_D)+bet_pH_D*(Hol/Kd_Hol_D+Hol*NAD/Kd_NAD_Hol_D/Kd_NAD_D)+gam_pH_D*(NADH*Hal/Kd_Hal_NADH_D/Kd_Hal_D+Hal/Kd_Hal_D+NAD*Hal/Kd_Hal_NAD_D/Kd_Hal_D+His*NADH/Kd_NADH_His_D/Kd_NADH_D+His/Kd_His_D)",
  "(1+L_dm*F_dm^(n-1)*H_dm^n)/(1+L_dm*(F_dm*H_dm)^n)",
  "V___5___*2.000-V___7___",
  "SDH*((kf_SDH/(1+Sal/Ki_Sal_SDH))*Suc_SDH*Q_SDH-kr_SDH*Fum_SDH*QH2_SDH)/(1+Suc_SDH+Q_SDH*Km_i_Suc_SDH/Kd_es_Suc_SDH+Suc_SDH*Q_SDH+Fum_SDH+Km_Fum_SDH*QH2_SDH/Kd_ef_Fum_SDH+Fum_SDH*QH2_SDH)",
  "1/v_mix",
  "V1*k2*(A1-A2)",
  "t/60",
  "k*(S-X1)/(1+X6^n/Ki^n)",
  "23*s_4*exp(d*12)",
  "rrr*pow(rrr, q)",
  "45*min2(eee*33, k_1)",
  "koff*min3(1,fun1,fun2)",
  "k0*sin(t)",
  "sqrt(e,r)",
  "abs(-ppp)"
];